export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const SELECT_SEASON = 'SELECT_SEASON';
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS';
